name: "Daily FCM Topic Push"

on:
  schedule:
   - cron: "*/5 * * * *"
  workflow_dispatch: {}

jobs:
  send-topic-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (v18)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Run send-topic.js
        working-directory: ./server
        env:
          FIREBASE_SERVICE_ACCOUNT_BASE64: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
        run: node send-topic.js